<?php
/**
 * @file
 * Code for the CLAIR Groups feature.
 */

include_once 'clair_groups.features.inc';

/**
 * Alters the title and description of the OG group reference field widget
 */
function clair_field_widget_form_alter(&$element, &$form_state, $context) {
  if(isset($element['#field_name']) && $element['#field_name']=='og_group_ref') {
    $element['#title'] = t('Your Collections');
    $element['#description'] = t('Associate this content with Collections you mangage.');
  }
}
